---
title: "SHELF - Spatially Weighted Heatmap(s)"
author: "Michael Schram"
date: "2022-12-09"
output: 
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This script is used to generate spatially-weighted heatmaps based on the
Metabarcoding results of the CUFES data

```{r, Libraries & Raw Data Import}
# Load package libraries
library(tidyverse)
library(ggplot2)
library(readxl)
library(sf)
library(mapview)
library(ggmap)

# Import station coordinates and depth. 
Sites <- read_xlsx("../1. Data/Fish Egg Metabarcoding Master Spreadsheet 2022-11-10.xlsx",
                   sheet = "Cruise-Station IDs")

# Import raw metabarcoding data
Eggs  <- read_xlsx("../1. Data/Fish Egg Metabarcoding Master Spreadsheet 2022-11-10.xlsx",
                   sheet = "QAQCd-2019 metabarcoding") %>%
  drop_na() # Remove last row of "Total" values.

# Query and store unique habitat types
Habitats <- unique(Eggs$Habitat)
```

```{r}
# Set projection coordinate system of Albers Equal Area, which has the units of meters instead of degrees
Sites_sf1 <- st_as_sf(Sites, 
                      coords = c("Longitude", "Latitude"), 
                      crs = 4269)

mapview(Sites_sf1)


library("rnaturalearth")
library("rnaturalearthdata")
theme_set(theme_bw())

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ggplot(data = world) +
  geom_sf(fill = "antiquewhite") +
  coord_sf(xlim = c(-85.5, -80.0), ylim = c(27.0, 30.50), expand = FALSE) + 
  theme(panel.grid.major = element_line(color = gray(.5), 
                                        linetype = "dashed", 
                                        size = 0.5), 
        panel.background = element_rect(fill = "aliceblue"))

```